services:
  - type: web
    name: gatherly-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 18
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: gatherly-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 5001